# Generated by Django 5.2.3 on 2026-01-13 18:39

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Store",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="分店名稱")),
                (
                    "slug",
                    models.SlugField(
                        help_text="例如：main 或 branch1",
                        unique=True,
                        verbose_name="網址辨識碼",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否營業中"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="商品名稱")),
                ("price", models.PositiveIntegerField(verbose_name="單價(元)")),
                (
                    "description",
                    models.CharField(blank=True, max_length=100, verbose_name="描述"),
                ),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products",
                        to="ordering.store",
                        verbose_name="所屬分店",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "phone_tail",
                    models.CharField(max_length=4, verbose_name="手機後4碼"),
                ),
                ("items", models.JSONField(default=list, verbose_name="訂單內容")),
                ("subtotal", models.PositiveIntegerField(verbose_name="小計")),
                ("total", models.PositiveIntegerField(verbose_name="總額")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "訂單確認中"),
                            ("confirmed", "訂單已成立"),
                            ("preparing", "訂單製作中"),
                            ("completed", "訂單完成"),
                            ("arrived", "客人已到櫃檯"),
                            ("final", "交易結案"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="訂單狀態",
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orders",
                        to="ordering.store",
                        verbose_name="所屬分店",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
