# Generated by Django 6.0.1 on 2026-01-23 13:27

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='例如：飲品系列', max_length=50, verbose_name='分類名稱')),
                ('slug', models.SlugField(help_text='對應前端 ID，例如：drink, tanghulu', verbose_name='分類代碼')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='顯示順序')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否啟用')),
            ],
            options={
                'verbose_name': '商品分類',
                'verbose_name_plural': '商品分類',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='分店名稱')),
                ('slug', models.SlugField(help_text='例如：main 或 branch1', unique=True, verbose_name='網址辨識碼')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否營業中')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='商品名稱')),
                ('price', models.PositiveIntegerField(verbose_name='單價(元)')),
                ('description', models.CharField(blank=True, max_length=100, verbose_name='短描述(如：口味二選一)')),
                ('flavor_options', models.CharField(blank=True, help_text='若需前端顯示下拉選單，請輸入選項並用逗號隔開。例：紅豆,花生,芝麻', max_length=200, verbose_name='口味選項')),
                ('stock', models.IntegerField(default=99, verbose_name='剩餘庫存')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否供應')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='ordering.category', verbose_name='商品分類')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='ordering.store', verbose_name='所屬分店')),
            ],
            options={
                'verbose_name': '商品',
                'verbose_name_plural': '商品',
                'ordering': ['category__sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_tail', models.CharField(max_length=4, verbose_name='手機後4碼')),
                ('payment_method', models.CharField(choices=[('cash', '現金'), ('linepay', 'LINE Pay')], default='cash', max_length=10, verbose_name='付款方式')),
                ('items', models.JSONField(default=list, verbose_name='訂單內容')),
                ('subtotal', models.PositiveIntegerField(default=0, verbose_name='小計')),
                ('total', models.PositiveIntegerField(default=0, verbose_name='總額')),
                ('linepay_transaction_id', models.CharField(blank=True, max_length=50, null=True)),
                ('linepay_refunded', models.BooleanField(default=False)),
                ('linepay_refund_transaction_id', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(choices=[('pending', '訂單確認中'), ('confirmed', '訂單已成立'), ('preparing', '訂單製作中'), ('completed', '訂單完成'), ('arrived', '客人已到櫃檯'), ('final', '交易結案'), ('cancelled', '已取消')], default='pending', max_length=20, verbose_name='訂單狀態')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='ordering.store', verbose_name='所屬分店')),
            ],
            options={
                'verbose_name': '訂單',
                'verbose_name_plural': '訂單',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='category',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='ordering.store', verbose_name='所屬分店'),
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('store', 'slug')},
        ),
    ]
