# Generated by Django 5.2.3 on 2026-01-13 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ordering", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "訂單確認中"),
                    ("confirmed", "訂單已成立"),
                    ("preparing", "訂單製作中"),
                    ("completed", "訂單完成"),
                    ("arrived", "客人已到櫃檯"),
                    ("final", "交易結案"),
                    ("cancelled", "已取消"),
                ],
                default="pending",
                max_length=20,
                verbose_name="訂單狀態",
            ),
        ),
    ]
