# Generated by Django 5.2.3 on 2026-01-15 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ordering", "0002_alter_order_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="是否供應"),
        ),
        migrations.AddField(
            model_name="product",
            name="stock",
            field=models.IntegerField(default=99, verbose_name="剩餘庫存"),
        ),
        migrations.AlterField(
            model_name="order",
            name="subtotal",
            field=models.PositiveIntegerField(default=0, verbose_name="小計"),
        ),
        migrations.AlterField(
            model_name="order",
            name="total",
            field=models.PositiveIntegerField(default=0, verbose_name="總額"),
        ),
    ]
