# Generated by Django 5.2.3 on 2026-01-15 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "ordering",
            "0003_product_is_active_product_stock_alter_order_subtotal_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="payment_method",
            field=models.CharField(
                choices=[("cash", "現金"), ("linepay", "LINE Pay")],
                default="cash",
                max_length=10,
                verbose_name="付款方式",
            ),
        ),
    ]
