# Generated by Django 6.0.1 on 2026-01-16 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordering', '0004_order_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='linepay_refund_transaction_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='linepay_refunded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='linepay_transaction_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
