# Generated by Django 6.0.1 on 2026-01-17 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordering', '0005_order_linepay_refund_transaction_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at'], 'verbose_name': '訂單', 'verbose_name_plural': '訂單'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['category', 'id'], 'verbose_name': '商品', 'verbose_name_plural': '商品'},
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('drink', '飲品系列'), ('tanghulu', '糖葫蘆系列'), ('mochi', 'Q軟麻糬系列'), ('dessert', '草莓甜點系列')], default='dessert', max_length=20, verbose_name='商品分類'),
        ),
        migrations.AddField(
            model_name='product',
            name='flavor_options',
            field=models.CharField(blank=True, help_text='若需前端顯示下拉選單，請輸入選項並用逗號隔開。例：紅豆,花生,芝麻', max_length=200, verbose_name='口味選項'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.CharField(blank=True, max_length=100, verbose_name='短描述(如：口味二選一)'),
        ),
    ]
