# Generated by Django 6.0.1 on 2026-01-17 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordering', '0006_alter_order_options_alter_product_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('drink', '飲品系列'), ('tanghulu', '糖葫蘆系列'), ('mochi', 'Q軟麻糬系列'), ('ichikomochi', '元寶草莓大福系列'), ('dessert', '草莓甜點系列')], default='dessert', max_length=20, verbose_name='商品分類'),
        ),
    ]
